# Basic
title: 狩猎者
subtitle: 欲师者，温故而知新；欲达者，吐故而纳新。
welcome_message: 欢迎您的到访！
description: 在这里记录下平时开发遇到的问题，方便日后查阅
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 浏览博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目(URL Scheme), url: 'StudyDemoApp://byurlSchemeOpen'}
    - {title: 跳转到app, description: 跳转到app, url: 'https://13225573109.github.io/wwdc/news/'}
    - {title: StudyDemo, description: 跳转到app, url: 'https://devxiaol.github.io/wwdc/news/'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: onevcat
    github: devXiaoL
    gplus: 107108267983477358170
    mail: langmbox@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
