# Basic
title: Vno Jekyll
subtitle: 欲师者，温故而知新；欲达者，吐故而纳新。
welcome_message: 这是记录平日学习遇到的各种问题的地方，欢迎您的到访！
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 浏览博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
